export const packages = [
  {
    id: 'honeymoon-trips',
    title: 'Honeymoon Trips',
    description: 'Curated romance, intimate stays, private experiences designed for couples seeking unforgettable moments together.',
    image: '/images/package-honeymoon.jpg',
    locationTag: 'Maldives to Paris',
    duration: '6N/7D',
    months: 'Sep - Mar',
    originalPrice: '85,000',
    price: '72,000',
    discountTag: 'Upto 13000 OFF',
    rating: 5,
    reviews: '(15k+)',
    isBestSeller: true,
  },
  {
    id: 'corporate-trips',
    title: 'Corporate Trips',
    description: 'Team bonding, offsites and company retreats that strengthen connections and boost team morale.',
    image: '/images/package-corporate.jpg',
    locationTag: 'Dubai / Singapore',
    duration: '3N/4D',
    months: 'All Year',
    originalPrice: '45,000',
    price: '38,000',
    discountTag: 'Upto 7000 OFF',
    rating: 4.7,
    reviews: '(4k+)',
    isBestSeller: false,
  },
  {
    id: 'bachelor-bachelorette',
    title: 'Bachelor / Bachelorette',
    description: 'Celebrate the last wild chapter in style with carefully planned adventures and memorable experiences.',
    image: '/images/package-bachelor.jpg',
    locationTag: 'Goa / Thailand',
    duration: '4N/5D',
    months: 'Oct - Feb',
    originalPrice: '35,000',
    price: '28,000',
    discountTag: 'Upto 7000 OFF',
    rating: 4.8,
    reviews: '(9k+)',
    isBestSeller: true,
  },
  {
    id: 'family-trips',
    title: 'Family Trips',
    description: 'Safe, fun and memorable experiences for every generation, from kids to grandparents.',
    image: '/images/package-family.jpg',
    locationTag: 'Kerala / Europe',
    duration: '7N/8D',
    months: 'Apr - Jun',
    originalPrice: '60,000',
    price: '52,000',
    discountTag: 'Upto 8000 OFF',
    rating: 4.9,
    reviews: '(12k+)',
    isBestSeller: false,
  },
  {
    id: 'solo-trips',
    title: 'Solo Trips',
    description: 'Travel your way — free, fearless, fully alive. Perfect for self-discovery and personal growth.',
    image: '/images/package-solo.jpg',
    locationTag: 'Spiti / Vietnam',
    duration: '9N/10D',
    months: 'May - Oct',
    originalPrice: '25,000',
    price: '21,500',
    discountTag: 'Upto 3500 OFF',
    rating: 4.9,
    reviews: '(11k+)',
    isBestSeller: true,
  },
  {
    id: 'adventure-tours',
    title: 'Adventure Tours',
    description: 'Thrilling expeditions for adrenaline seekers with expert guides and safety as our priority.',
    image: '/images/package-adventure.jpg',
    locationTag: 'Ladakh / Everest',
    duration: '11N/12D',
    months: 'Jun - Sep',
    originalPrice: '42,000',
    price: '37,000',
    discountTag: 'Upto 5000 OFF',
    rating: 4.8,
    reviews: '(7k+)',
    isBestSeller: false,
  },
]

export const blogs = [
  {
    id: 'blog-1',
    title: 'Hidden Gems of Mountain Valleys',
    description: 'Discover hidden gems and local experiences that will change your perspective on travel.',
    image: '/images/blog-1.jpg',
  },
  {
    id: 'blog-2',
    title: 'Exploring Ancient Temples & Culture',
    description: 'Journey through time and immerse yourself in centuries of history and tradition.',
    image: '/images/blog-2.jpg',
  },
  {
    id: 'blog-3',
    title: 'Coastal Towns: A Vibrant Adventure',
    description: 'Experience the colorful charm of coastal living and embrace the Mediterranean lifestyle.',
    image: '/images/blog-3.jpg',
  },
  {
    id: 'blog-4',
    title: 'Mountain Retreats & Serenity',
    description: 'Find peace in the high altitudes with our guide to the best mountain escapes.',
    image: '/images/hero-destination.jpg',
  },
  {
    id: 'blog-5',
    title: 'Desert Nights: Under the Stars',
    description: 'A magical guide to experiencing the silence and beauty of the desert at night.',
    image: '/images/package-corporate.jpg',
  },
]

export const features = [
  {
    icon: '✈️',
    title: 'Expert Curation',
    description: 'Handpicked destinations and experiences curated by seasoned travel experts who know every detail.',
  },
  {
    icon: '🏨',
    title: 'Premium Stays',
    description: 'Luxury accommodations with personalized service at the finest hotels and resorts worldwide.',
  },
  {
    icon: '👥',
    title: 'Community First',
    description: 'Travel with like-minded adventurers and create lifelong connections on the road.',
  },
  {
    icon: '🎯',
    title: '24/7 Support',
    description: 'Round-the-clock assistance ensuring your peace of mind throughout your journey.',
  },
  {
    icon: '💎',
    title: 'Exclusive Access',
    description: 'VIP experiences and insider access that regular tourists simply cannot get.',
  },
  {
    icon: '🌍',
    title: 'Global Network',
    description: 'Access to our extensive network of partners across 50+ countries for seamless travel.',
  },
]

export const testimonials = [
  {
    text: 'More than the place; it was the co-travelers! More than the group, it was our very own guide who made us feel loved, heard and seen without any judgments. We all were ourselves and the credit goes to the incredible team. Cheers!',
    author: 'Sakshi Sachdev',
    destination: 'Thailand',
    avatar: '/images/avatar-1.jpg',
  },
  {
    text: 'Most people go on holiday to escape stress, but my experience was the complete opposite. They promised slow travel, and they absolutely delivered. We started as strangers. By the end, we were an inseparable family. That\'s the magic created here.',
    author: 'James Watson',
    destination: 'Thailand',
    avatar: '/images/avatar-2.jpg',
  },
  {
    text: 'Just got back from an amazing trip and I honestly didn\'t expect it to be this fun and well-managed. The itinerary was perfectly planned, stays were comfortable, and there was a perfect balance between exploring and enjoying the vibe. Would 100% recommend!',
    author: 'Shriya Srivastava',
    destination: 'Thailand',
    avatar: '/images/avatar-3.jpg',
  },
  {
    text: 'The attention to detail was phenomenal. Every moment felt carefully curated, yet spontaneous. The guides were knowledgeable and warm. I made friends from different parts of the world and we\'re planning our next adventure together already!',
    author: 'Michael Chen',
    destination: 'Bali',
    avatar: '/images/avatar-1.jpg',
  },
]

export const groupTrips = [
  {
    id: 'best-of-europe-13-days',
    title: 'Best of Europe',
    locationTag: 'Paris to Rome',
    description: 'Explore France, Belgium, Netherlands, Germany, Switzerland, Austria and Italy in one grand 13-day adventure.',
    image: '/images/package-adventure.jpg',
    duration: '12N/13D',
    months: 'May - Oct',
    originalPrice: '3,35,000',
    price: '3,00,000',
    discountTag: 'Upto 35000 OFF',
    rating: 4.9,
    reviews: '(6k+)',
    isBestSeller: true,
  },
  {
    id: 'grand-wonders-of-europe-16-days',
    title: 'Grand Wonders of Europe',
    locationTag: 'London to Rome',
    description: 'Explore UK, France, Belgium, Netherlands, Germany, Switzerland, Austria and Italy in one epic 16-day grand tour.',
    image: '/images/package-adventure.jpg',
    duration: '15N/16D',
    months: 'May - Oct',
    originalPrice: '4,10,000',
    price: '3,71,000',
    discountTag: 'Upto 39000 OFF',
    rating: 4.9,
    reviews: '(8k+)',
    isBestSeller: true,
  },
]
